version: "3.5"
name: barger
services:
  admin-panel-frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8089:3000"
#    env_file:
#      - .env
