export type StrokeIconName =
  | "add-square"
  | "closedeye"
  | "exit"
  | "eye-closed"
  | "eye"
  | "folder-open"
  | "gallery"
  | "hamburger"
  | "home-2"
  | "key"
  | "magnifier"
  | "moon"
  | "openeye"
  | "pen-new-square"
  | "settings"
  | "sun"
  | "trash-bin"
  | "user-circle"
  | "users-group-two"

export type FillIconName =
  | "arrow-left-alt"
  | "cross"
  | "folder-open"
  | "gallery"
  | "home-2"
  | "info-circle"
  | "maximize"
  | "minimize"
  | "pen-new-square"
  | "pencil"
  | "settings"
  | "tuning"
  | "user-circle"
  | "users-group-two"
