export type StrokeIconName =
  | "exit"
  | "folder-open"
  | "gallery"
  | "hamburger"
  | "home-2"
  | "pen-new-square"
  | "settings"
  | "user-circle"
  | "users-group-two"

export type FillIconName =
  | "folder-open"
  | "gallery"
  | "home-2"
  | "maximize"
  | "minimize"
  | "pen-new-square"
  | "settings"
  | "user-circle"
  | "users-group-two"