export type StrokeIconName =
  | "add-square"
  | "exit"
  | "folder-open"
  | "gallery"
  | "hamburger"
  | "home-2"
  | "key"
  | "magnifer"
  | "moon"
  | "pen-new-square"
  | "settings"
  | "sun"
  | "trash-bin"
  | "user-circle"
  | "users-group-two"

export type FillIconName =
  | "arrow-left-alt"
  | "cross"
  | "folder-open"
  | "gallery"
  | "home-2"
  | "maximize"
  | "minimize"
  | "pen-new-square"
  | "settings-edit"
  | "settings"
  | "settings-loop"
  | "settings-parametr"
  | "settings-plus"
  | "settings-recycle"
  | "tuning"
  | "user-circle"
  | "users-group-two"
