/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export interface CreateCarBodyRequest {
  liftingCapacity: number;
  number: string;
  volume: number;
}
