/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export interface CreateOrderResponse {
  days: number;
  distance: number;
  id: number;
  productId: number;
  start: number;
  volume: number;
  weight: number;
}
